"""
TechOpsKM - Build Search Index

Reads markdown from:
1. OBSIDIAN_VAULT (raw SOP processed by km_processor)
2. WIKI_DIR (wiki articles generated by km_wiki.py)

Builds a combined JSON index and uploads it to SFTP.
Run after km_processor.py and km_wiki.py complete.
"""
from dotenv import load_dotenv
load_dotenv()

import os
import re
import json
import sys
from pathlib import Path
from datetime import datetime

from km_sftp import upload_to_path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE_DIR = Path(__file__).parent.parent
RUNTIME_ROOT = Path(os.environ.get("KM_RUNTIME_ROOT", BASE_DIR / "runtime"))
VAULT_DIR = Path(os.environ.get("OBSIDIAN_VAULT", RUNTIME_ROOT / "vault"))
WIKI_DIR = Path(os.environ.get("WIKI_DIR", VAULT_DIR / "wiki"))
INDEX_FILE = VAULT_DIR / "search_index.json"
SFTP_INDEX_PATH = "/sop/aikms/search_index.json"

SKIP_DIRS = {"_archive", ".obsidian", ".trash", "node_modules"}
SKIP_VAULT_ROOT_DIRS = {"engineering", "qa", "cross-functional", "decision-support"}

BODY_LIMIT_WIKI = 6000
BODY_LIMIT_SOP = 5000

DEPT_MAP = {
    "Engineering": "Engineering",
    "QA": "Quality Assurance",
    "Quality Control": "Quality Control",
    "QS": "Quality System",
    "Quality Assurance": "Quality Assurance",
    "Quality System": "Quality System",
    "Cross-functional": "Cross-functional",
    "Cross Functional": "Cross-functional",
    "Warehouse": "Warehouse",
    "Production": "Production",
    "PPIC": "PPIC",
    "R&D": "R&D",
    "HRGA": "HR & GA",
    "HR & GA": "HR & GA",
    "HSE": "HSE",
    "Formulation": "Formulation",
    "Downstream": "Downstream",
    "Others": "Others",
}

FOLDER_DEPT_MAP = {
    "Departement Engineering": "Engineering",
    "Engineering": "Engineering",
    "Departement Quality Assurance": "Quality Assurance",
    "Quality Assurance": "Quality Assurance",
    "Quality Control": "Quality Control",
    "Departement Quality System": "Quality System",
    "Quality System": "Quality System",
    "Warehouse": "Warehouse",
    "Production": "Production",
    "R&D": "R&D",
    "HSE": "HSE",
    "HRGA": "HR & GA",
    "HR & GA": "HR & GA",
}

CODE_DEPT_MAP = {
    "EN": "Engineering",
    "QA": "Quality Assurance",
    "QC": "Quality Control",
    "QS": "Quality System",
    "MM": "Warehouse",
    "PD": "Production",
    "FF": "Production",
    "DS": "Production",
    "RD": "R&D",
    "HS": "HSE",
    "HR": "HR & GA",
}


def normalize_dept(dept):
    return DEPT_MAP.get(dept, dept)


def _clean_meta_value(value):
    return value.strip().strip('"\'').strip()


def extract_fm(content, field):
    field_pattern = re.escape(field).replace(r"\ ", r"\s+")
    patterns = [
        rf"^{field_pattern}:\s*(.+)$",
        rf"^\*\*{field_pattern}\*\*:\s*(.+)$",
    ]
    for pattern in patterns:
        match = re.search(pattern, content, re.MULTILINE | re.IGNORECASE)
        if match:
            return _clean_meta_value(match.group(1))
    return ""


def extract_first(content, fields):
    for field in fields:
        value = extract_fm(content, field)
        if value:
            return value
    return ""


def normalize_sop_code(value, revision=""):
    raw = _clean_meta_value(str(value or ""))
    if not raw:
        return ""

    match = re.search(
        r"SOP\s*[/\-\s]*EBI\s*[/\-\s]*([A-Z]{2,3})\s*[/\-\s]*(\d{3})(?:[.\-\s]*(\d{1,2}))?",
        raw,
        flags=re.IGNORECASE,
    )
    if not match:
        return ""

    dept_code = match.group(1).upper()
    number = match.group(2)
    rev = match.group(3) or ""
    if not rev and revision:
        rev_match = re.search(r"\d{1,2}", str(revision))
        if rev_match:
            rev = rev_match.group(0)
    if rev:
        return f"SOP-EBI-{dept_code}-{number}.{int(rev):02d}"
    return f"SOP-EBI-{dept_code}-{number}"


def extract_sop_code(content, fallback_name=""):
    revision = extract_first(content, ["revision", "Revision", "Rev", "Rev."])
    candidates = [
        extract_first(content, ["sop_number", "sop_num", "SOP Number", "SOP No", "SOP No.", "SOP"]),
        fallback_name,
        content[:2500],
    ]
    for candidate in candidates:
        sop_code = normalize_sop_code(candidate, revision)
        if sop_code:
            return sop_code
    return ""


def infer_dept_from_path(rel_parts, sop_num=""):
    parts = list(rel_parts or [])
    if parts and parts[0] == "raw" and len(parts) > 1:
        mapped = FOLDER_DEPT_MAP.get(parts[1])
        if mapped:
            return mapped
    for part in parts:
        mapped = FOLDER_DEPT_MAP.get(part)
        if mapped:
            return mapped

    code_match = re.search(r"SOP-EBI-([A-Z]{2,3})-", sop_num or "", flags=re.IGNORECASE)
    if code_match:
        return CODE_DEPT_MAP.get(code_match.group(1).upper(), "")
    return ""


def normalize_knowledge_title(title, fallback=""):
    value = _clean_meta_value(title)
    value = re.sub(
        r"^\s*SOP\s*[/\-\s]*EBI\s*[/\-\s]*[A-Z]{2,3}\s*[/\-\s]*\d{3}(?:[.-]\d{2})?(?:\s*[—\-:]\s*|\s+)",
        "",
        value,
        flags=re.IGNORECASE,
    ).strip()
    value = re.sub(r"\s+", " ", value).strip()
    if value and not re.match(r"(?i)^SOP\s*[/\-\s]*EBI", value):
        return value
    return str(fallback or "").replace("-", " ").replace("_", " ").title()


def extract_title(content, fallback):
    title = extract_first(content, ["title", "Title"])
    if title:
        return normalize_knowledge_title(title, fallback)
    match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    if match:
        return normalize_knowledge_title(_clean_meta_value(match.group(1)), fallback)
    return normalize_knowledge_title(fallback, fallback)


def extract_tags(content):
    match = re.search(r"^tags:\s*(.+)$", content, re.MULTILINE)
    if not match:
        return []
    raw = re.sub(r"[\[\]]", "", match.group(1).strip())
    return [tag.strip().strip('"\'') for tag in raw.split(",") if tag.strip()]


def get_body(content):
    if content.startswith("---"):
        end = content.find("---", 3)
        if end > 0:
            return content[end + 3 :].strip()
    return content.strip()


def clean_body(body, max_chars):
    body = re.sub(r"<!--.*?-->", "", body, flags=re.DOTALL)
    body = re.sub(r"!\[.*?\]\(.*?\)", "", body)
    body = re.sub(r"\n{3,}", "\n\n", body)
    return body[:max_chars].strip()


def build_tags_string(title, sop_num, dept, rel_path, extra_tags=None):
    parts = [
        rel_path.lower().replace("/", " ").replace("-", " ").replace("_", " "),
        title.lower(),
        sop_num.lower() if sop_num else "",
        dept.lower() if dept else "",
    ]
    if extra_tags:
        parts.extend(tag.lower() for tag in extra_tags)
    return " ".join(part for part in parts if part)


def process_wiki(docs, seen_ids):
    if not WIKI_DIR.exists():
        print(f"[Index] WIKI_DIR not found: {WIKI_DIR} - skipping wiki scan")
        return

    wiki_count = 0
    for md in WIKI_DIR.rglob("*.md"):
        if any(part in SKIP_DIRS for part in md.parts):
            continue

        try:
            content = md.read_text(encoding="utf-8", errors="ignore")
            body = get_body(content)
            rel_path = "wiki/" + md.relative_to(WIKI_DIR).as_posix()

            if rel_path in seen_ids:
                continue

            title = extract_title(content, md.stem.replace("-", " ").title())
            sop_num = extract_sop_code(content, md.stem)
            dept = normalize_dept(
                extract_first(content, ["department", "dept", "Department", "Dept"]) or
                infer_dept_from_path(md.relative_to(WIKI_DIR).parts, sop_num) or
                "Engineering"
            )
            doc_type = extract_first(content, ["type", "Type"]) or "wiki"
            tags = extract_tags(content)

            kw_match = re.search(r"Keywords:\s*\[([^\]]+)\]", content)
            if kw_match:
                tags.extend(keyword.strip() for keyword in kw_match.group(1).split(","))

            docs.append({
                "id": rel_path,
                "title": title,
                "sop_num": sop_num,
                "dept": dept,
                "department": dept,
                "type": doc_type,
                "body": clean_body(body, BODY_LIMIT_WIKI),
                "tags": build_tags_string(title, sop_num, dept, rel_path, tags),
                "source": "wiki",
            })
            seen_ids.add(rel_path)
            wiki_count += 1
        except Exception as exc:
            print(f"  [WARN] Skip wiki {md.name}: {exc}")

    print(f"[Index] ✓ Wiki articles indexed: {wiki_count}")


def process_vault(docs, seen_ids):
    if not VAULT_DIR.exists():
        print(f"[Index] VAULT_DIR not found: {VAULT_DIR} - skipping vault scan")
        return

    vault_count = 0
    for md in VAULT_DIR.rglob("*.md"):
        if any(part in SKIP_DIRS or part.startswith(".") for part in md.parts):
            continue
        if md.name == "techops-km-index.md":
            continue

        try:
            content = md.read_text(encoding="utf-8", errors="ignore")
            body = get_body(content)
            rel_path = md.relative_to(VAULT_DIR).as_posix()
            rel_parts = md.relative_to(VAULT_DIR).parts

            if rel_parts and rel_parts[0] in SKIP_VAULT_ROOT_DIRS:
                continue
            if rel_path in seen_ids:
                continue

            title = extract_title(content, md.stem)
            sop_num = extract_sop_code(content, md.stem)
            dept = normalize_dept(
                extract_first(content, ["department", "dept", "Department", "Dept"]) or
                infer_dept_from_path(rel_parts, sop_num) or
                "Engineering"
            )
            doc_type = extract_first(content, ["type", "Type"]) or "raw"
            tags = extract_tags(content)

            docs.append({
                "id": rel_path,
                "title": title,
                "sop_num": sop_num,
                "dept": dept,
                "department": dept,
                "type": doc_type,
                "body": clean_body(body, BODY_LIMIT_SOP),
                "tags": build_tags_string(title, sop_num, dept, rel_path, tags),
                "source": "vault",
            })
            seen_ids.add(rel_path)
            vault_count += 1
        except Exception as exc:
            print(f"  [WARN] Skip vault {md.name}: {exc}")

    print(f"[Index] ✓ Vault SOP docs indexed: {vault_count}")


def build_index():
    print("[Index] Starting build...")
    print(f"[Index]   VAULT_DIR : {VAULT_DIR}")
    print(f"[Index]   WIKI_DIR  : {WIKI_DIR}")

    docs = []
    seen_ids = set()

    process_wiki(docs, seen_ids)
    process_vault(docs, seen_ids)

    dept_dist = {}
    for doc in docs:
        dept_dist[doc["dept"]] = dept_dist.get(doc["dept"], 0) + 1
    print(f"[Index] Dept distribution: {dept_dist}")

    source_dist = {}
    for doc in docs:
        source_dist[doc["source"]] = source_dist.get(doc["source"], 0) + 1
    print(f"[Index] Source distribution: {source_dist}")

    index = {
        "generated": datetime.now().isoformat(),
        "total": len(docs),
        "docs": docs,
    }

    INDEX_FILE.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[Index] ✓ Generated {len(docs)} docs -> {INDEX_FILE}")

    print(f"[Index] Upload ke SFTP ({SFTP_INDEX_PATH})...")
    ok, _ = upload_to_path(INDEX_FILE, SFTP_INDEX_PATH)
    if ok:
        print("[Index] ✓ Upload berhasil")
    else:
        print("[Index] ✗ Upload gagal - cek koneksi/config SFTP")


if __name__ == "__main__":
    build_index()
