name: Test SFTP Connection

on:
  workflow_dispatch:

jobs:
  test-sftp:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Test SFTP connection
        env:
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          if [ -z "$SSHPASS" ]; then
            echo "SFTP_PASSWORD is EMPTY"
            exit 1
          fi

          sshpass -e sftp \
            -o StrictHostKeyChecking=no \
            -P 7235 \
            aikms@renodoc.asiatirtapharma.com <<'EOF'
          pwd
          ls
          cd sop
          ls
          bye
          EOF